title: Dian Ji
description: Department of Earth and Planetary Sciences, University of Tennessee
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
url: Dian01811.GitHub.io
[CV](https://dian01811.github.io/files/CV.pdf)
