title: Dian Ji (吉点)
description: Department of Earth, Environmental and Planetary Sciences, Rice University
show_downloads: true
params.favicon: true
google_analytics:
theme: jekyll-theme-cayman
url: Dian01811.GitHub.io
plugins:
  - jekyll-seo-tag
