title: Dian Ji (吉点)
description: Department of Earth and Planetary Sciences, University of Tennessee
show_downloads: true
params.favicon: true
google_analytics:
theme: jekyll-theme-cayman
url: Dian01811.GitHub.io
